config/routes.rb
Rails.application.routes.draw do

  root "restaurants#index"
  resources :restaurants do
    resources :reviews

  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :rating, numericality: true, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }
  validates :content, presence: true
  validates :restaurant_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end


  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]
  def new
    @review = Review.new
  end

  def create
    # @restaurant.review.build()
    # # <=> Review.new(restaurant: @restaurant)
    # @restaurant.review.create()
    # # <=> Review.create(restaurant: @restaurant)

    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end

  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lacuillere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<h1>Here is the restaurants' list !!</h1>

<%= link_to 'create new restaurant', new_restaurant_path %>
<hr>

<% @restaurants.each do |restaurant| %>
  <p>
    <strong><%= restaurant.name %></strong>
     - Category : <%= restaurant.category %>
     - <%= link_to 'Details', restaurant_path(restaurant) %>
  </p>

<% end %>

app/views/restaurants/new.html.erb
<h1>Please fill the form to create a new restaurant</h1>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<ul>
  <li><%= @restaurant.address %></li>
  <li><%= @restaurant.phone_number %></li>
  <li><%= @restaurant.category %></li>
</ul>

<%= link_to 'Add a review', new_restaurant_review_path(@restaurant) %>
<% if @restaurant.reviews == nil %>
  <%= "No review for this restaurant" %>
<% else %>
  <h2>Reviews</h2>
  <% @restaurant.reviews.each do |review| %>
    <p>Rating : <%= review.rating %> - Content : <%= review.content %></p>
  <% end %>
<% end %>

app/views/reviews/new.html.erb
<h1>Please add a new review to this restaurant</h1>

<%= form_for @review, url: restaurant_reviews_path(@restaurant) do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>